[project]
name = "destructive-acoustic-interference"
version = "0.1.0"
description = "An experimental demonstration of destructive acoustic intereference."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.3",
    "sounddevice>=0.5.2",
]
